name: Sync and Deploy

on:
  push:
    branches:
      - main

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v2
        with:
          repository: hyeri1126/MSA-FE
          token: ${{ secrets.DEPLOY_PAT }}
          ref: main
          
      - name: Configure Git
        run: |
          git config --global user.name "hyeri1126"
          git config --global user.email "hyeri1126@ewhain.net"
          
      - name: Configure upstream
        run: |
          git remote add upstream https://github.com/woorifisa-projects-3rd/MSA-FE.git
          
      - name: Sync with upstream
        run: |
          git fetch upstream main
          git merge upstream/main --allow-unrelated-histories
          
      - name: Push changes
        run: |
          git push origin main